name: Vacancy Management Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Application Build
        run: mvn clean install -DskipTests

      - name: Docker hub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Imagen Build
        run: docker build -t caiquepirs/vacancy_management .

      - name: Imagen Push
        run: docker push caiquepirs/vacancy_management

